name: Fabrica Ebenezer
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      # ESTA ES LA PIEZA NUEVA: Le pedimos a GitHub que traiga el motor oficial
      - name: Descargar Motor Android Oficial
        run: gradle wrapper
        
      - name: Dar permiso al motor
        run: chmod +x gradlew
        
      - name: Fabricar APK
        run: ./gradlew assembleDebug

      - name: Entregar App
        uses: actions/upload-artifact@v4
        with:
          name: App-Ebenezer
          path: app/build/outputs/apk/debug/*.apk