name: Fabrica Ebenezer Profesional

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Extraer codigo del ensamblador
      uses: actions/checkout@v4

    - name: Preparar el entorno Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Iniciar Motor Oficial Robusto
      uses: gradle/actions/setup-gradle@v3

    - name: Ensamblar APK Final
      run: gradle assembleDebug

    - name: Entregar App lista
      uses: actions/upload-artifact@v4
      with:
        name: App-Ebenezer
        path: app/build/outputs/apk/debug/*.apk